// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFTXhj-rnu6r9lvEbydYBiDKnapY1vt14',
    appId: '1:410990773259:web:dcbf5187e9962c951f730e',
    messagingSenderId: '410990773259',
    projectId: 'chat--app-4f71d',
    authDomain: 'chat--app-4f71d.firebaseapp.com',
    storageBucket: 'chat--app-4f71d.appspot.com',
    measurementId: 'G-NW1H8GYRKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0tQVwtKM_PN5wY0_9oaTrscN-_L15wFQ',
    appId: '1:410990773259:android:ec2faac31d295e2f1f730e',
    messagingSenderId: '410990773259',
    projectId: 'chat--app-4f71d',
    storageBucket: 'chat--app-4f71d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbNksbmf2aFukKWt34PzH8ecopISrSZs',
    appId: '1:410990773259:ios:9febfa71648017881f730e',
    messagingSenderId: '410990773259',
    projectId: 'chat--app-4f71d',
    storageBucket: 'chat--app-4f71d.appspot.com',
    iosClientId: '410990773259-m4rm04t5eeppal6mv6vmh0gjvmq7c748.apps.googleusercontent.com',
    iosBundleId: 'com.amrsalem.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbNksbmf2aFukKWt34PzH8ecopISrSZs',
    appId: '1:410990773259:ios:6d4981a83f9a464e1f730e',
    messagingSenderId: '410990773259',
    projectId: 'chat--app-4f71d',
    storageBucket: 'chat--app-4f71d.appspot.com',
    iosClientId: '410990773259-24bbv3ksh2mdfuac5vimsjrvh5p683vt.apps.googleusercontent.com',
    iosBundleId: 'com.amrsalem.chatapp.RunnerTests',
  );
}
